name: Deployment
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: deploy
        run: echo "Deploying"
